/**
 * [generator color](https://color.adobe.com/mythemes)
 * copy as xml
 * [xml to json](https://jsonformatter.org/xml-to-json)
 */
const palette = {
    'color': [
        {
            'name': 'My-Color-Theme-1',
            'hex': '#7CD9FF',
            'r': '124',
            'g': '217',
            'b': '255',
        },
        {
            'name': 'My-Color-Theme-2',
            'hex': '#FF2E8C',
            'r': '255',
            'g': '46',
            'b': '140',
        },
        {
            'name': 'My-Color-Theme-3',
            'hex': '#FA2F2F',
            'r': '250',
            'g': '47',
            'b': '47',
        },
        {
            'name': 'My-Color-Theme-4',
            'hex': '#FF4529',
            'r': '255',
            'g': '69',
            'b': '41',
        },
        {
            'name': 'My-Color-Theme-5',
            'hex': '#FF6224',
            'r': '255',
            'g': '98',
            'b': '36',
        },
        {
            'name': 'My-Color-Theme-6',
            'hex': '#FF8126',
            'r': '255',
            'g': '129',
            'b': '38',
        },
        {
            'name': 'My-Color-Theme-7',
            'hex': '#FFA126',
            'r': '255',
            'g': '161',
            'b': '38',
        },
        {
            'name': 'My-Color-Theme-8',
            'hex': '#FFBE33',
            'r': '255',
            'g': '190',
            'b': '51',
        },
        {
            'name': 'My-Color-Theme-9',
            'hex': '#FFD736',
            'r': '255',
            'g': '215',
            'b': '54',
        },
        {
            'name': 'My-Color-Theme-10',
            'hex': '#FFEF37',
            'r': '255',
            'g': '239',
            'b': '55',
        },
        {
            'name': 'My-Color-Theme-11',
            'hex': '#EEFF33',
            'r': '238',
            'g': '255',
            'b': '51',
        },
        {
            'name': 'My-Color-Theme-12',
            'hex': '#A1FF36',
            'r': '161',
            'g': '255',
            'b': '54',
        },
        {
            'name': 'My-Color-Theme-13',
            'hex': '#4DFF36',
            'r': '77',
            'g': '255',
            'b': '54',
        },
        {
            'name': 'My-Color-Theme-14',
            'hex': '#38FF5D',
            'r': '56',
            'g': '255',
            'b': '93',
        },
        {
            'name': 'My-Color-Theme-15',
            'hex': '#38FF98',
            'r': '56',
            'g': '255',
            'b': '152',
        },
        {
            'name': 'My-Color-Theme-16',
            'hex': '#45FFDA',
            'r': '69',
            'g': '255',
            'b': '218',
        },
        {
            'name': 'My-Color-Theme-17',
            'hex': '#40E5FF',
            'r': '64',
            'g': '229',
            'b': '255',
        },
        {
            'name': 'My-Color-Theme-18',
            'hex': '#38ACFF',
            'r': '56',
            'g': '172',
            'b': '255',
        },
        {
            'name': 'My-Color-Theme-19',
            'hex': '#3670FF',
            'r': '54',
            'g': '112',
            'b': '255',
        },
        {
            'name': 'My-Color-Theme-20',
            'hex': '#3D33FF',
            'r': '61',
            'g': '51',
            'b': '255',
        },
        {
            'name': 'My-Color-Theme-21',
            'hex': '#7639FF',
            'r': '118',
            'g': '57',
            'b': '255',
        },
        {
            'name': 'My-Color-Theme-22',
            'hex': '#AA36FF',
            'r': '170',
            'g': '54',
            'b': '255',
        },
        {
            'name': 'My-Color-Theme-23',
            'hex': '#D837FF',
            'r': '216',
            'g': '55',
            'b': '255',
        },
        {
            'name': 'My-Color-Theme-24',
            'hex': '#F030E2',
            'r': '240',
            'g': '48',
            'b': '226',
        },
    ],
};
