import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { AppMeta } from '@/components/layout/app-meta';
import { Providers } from '@/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    manifest: '/manifest.webmanifest',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning={process.env.NODE_ENV === 'development' ? true : false}
        >
            <head>
                <AppMeta />
            </head>
            <body className={inter.className}>
                <Providers>
                    <div className="flex min-h-screen w-full flex-col">{children}</div>
                </Providers>
            </body>
        </html>
    );
}
