import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { NavBar } from '@/components/layout/navbar';
import { Providers } from '@/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={process.env.NODE_ENV === 'development' ? true : false}>
            <body className={inter.className}>
                <Providers>
                    <div className="flex min-h-screen w-full flex-col">
                        <NavBar />
                        <main className="flex flex-grow w-full">{children}</main>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
